spring:
  application:
    name: BRT
  datasource:
    url: jdbc:postgresql://postgres:5432/brt
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081
